const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const load=()=>{assert.ok(fs.existsSync('dist/features/backtest-cost-stress.js'),'cost stress module must exist');return require('../dist/features/backtest-cost-stress');};
const input=()=>({context:{market:'stocks',instrument:'stock:us:AAPL',workspace:'research',dataSource:'fixture',strategyVersion:'fixture-v1',feeRate:0.001,slippage:0.002,seed:42},prices:[100,110,120],signals:[{timeIndex:0,direction:'buy'},{timeIndex:2,direction:'sell'}]});
test('nonlinear perpetual contracts never use the cash cost model',()=>{const {backtestCostStress}=load();assert.equal(backtestCostStress({...input(),context:{...input().context,market:'crypto',instrument:'crypto:deribit:BTC-PERPETUAL'}}).dataStatus,'unsupported');});
test('malformed volume and order constraints cannot create non-finite cost evidence',()=>{const {backtestCostStress}=load();for(const patch of [{volume:NaN},{volume:-1},{orderType:'limit',limitPrice:Infinity}])assert.equal(backtestCostStress({...input(),signals:[{timeIndex:0,direction:'buy',...patch}]}).dataStatus,'unavailable');});
test('cost stress replays the same inputs at 1x, 2x and 3x and reports curves and costs reproducibly',()=>{const {backtestCostStress}=load(),a=backtestCostStress(input()),b=backtestCostStress(input());assert.deepEqual(a,b);assert.equal(a.executionEnabled,false);assert.equal(a.scenarios.length,3);assert.ok(a.scenarios[2].totalFees>a.scenarios[0].totalFees);assert.ok(a.scenarios[2].totalReturnPct<a.scenarios[0].totalReturnPct);assert.match(a.inputHash,/^[a-f0-9]{64}$/);});
test('missing cost assumptions and nonlinear markets are explicit unavailable, not zero-cost evidence',()=>{const {backtestCostStress}=load(),data=input();delete data.context.feeRate;assert.equal(backtestCostStress(data).dataStatus,'unavailable');assert.equal(backtestCostStress({...input(),context:{...input().context,market:'options',instrument:'option:cboe:AAPL'}}).dataStatus,'unsupported');});
test('out-of-range signals and fabricated execution prices fail closed',()=>{const {backtestCostStress}=load();assert.match(backtestCostStress({...input(),signals:[{timeIndex:3,direction:'buy'}]}).reason,/未来|信号/);assert.match(backtestCostStress({...input(),signals:[{timeIndex:0,direction:'buy',price:1}]}).reason,/成交价/);});
test('experiment results and comparison keep costs with explicit scope warnings',()=>{const {backtestCostStress}=load();const source=fs.readFileSync('src/features/experiment-runner.ts','utf8');assert.match(source,/costStress:\s*backtestCostStress\(input\)/);assert.match(fs.readFileSync('src/features/experiment-comparison.ts','utf8'),/costStress:\s*row\.costStress/);assert.match(backtestCostStress(input()).warnings.join(' '),/资金费|强平/);});
