const test=require('node:test');const assert=require('node:assert/strict');const {JSDOM}=require('jsdom');const fs=require('node:fs');
test('production homepage wires contracts and workflow scripts with an isolated navigation entry',()=>{
 const page=require('./helpers/dashboard-source.cjs').readDashboardSource();assert.match(page,/src="\/contracts-workspace\.js\?/);assert.match(page,/src="\/workflow-polish\.js\?/);assert.match(page,/contracts: \['⇋', '永续与交割合约'\]/);assert.match(page,/async locateDay\(instrument,day\)/);
});
test('contracts appear only in crypto workspace and right library selection preserves venue identity',async()=>{
 const dom=new JSDOM('<main id="market-workspace-shell" data-market-scope="stocks" data-workspace="insider" data-instrument="stock:us:AAPL"><div id="center-workspace"></div><aside data-market-library="crypto"><div id="spot-list">BTC spot</div></aside></main>',{url:'https://test.invalid',runScripts:'outside-only'}),win=dom.window,shell=win.document.querySelector('main');let selected=null;
 win.fetch=async url=>({ok:true,json:async()=>url.includes('/catalog')?{success:true,dataStatus:'delayed',updatedAt:'2026-10-02',items:[{instrument:'crypto:gateio:BTC_USDT',name:'BTC_USDT',kind:'perpetual'}]}:{success:false,reason:'source unavailable'}});win.setWorkspaceInstrument=id=>{selected=id;shell.dataset.instrument=id;win.dispatchEvent(new win.Event('mm-workspace-context'));};
 win.eval(fs.readFileSync('src/web/public/contracts-workspace.js','utf8'));win.document.dispatchEvent(new win.Event('DOMContentLoaded'));await new Promise(r=>setTimeout(r,10));assert.equal(win.document.querySelector('#mm-contract-workspace').hidden,true);
 shell.dataset.marketScope='crypto';shell.dataset.workspace='contracts';win.dispatchEvent(new win.Event('mm-workspace-context'));await new Promise(r=>setTimeout(r,10));assert.equal(win.document.querySelector('#mm-contract-workspace').hidden,false);assert.equal(win.document.querySelector('#spot-list').classList.contains('mm-contract-hidden'),true);assert.match(win.document.querySelector('[data-contract-status]').textContent,/不是.*合约/);
 win.document.querySelector('[data-contract-id]').click();await new Promise(r=>setTimeout(r,10));assert.equal(selected,'crypto:gateio:BTC_USDT');assert.equal(win.document.querySelector('[data-contract-status]').textContent,'source unavailable');
 shell.dataset.marketScope='options';shell.dataset.workspace='greeks';win.dispatchEvent(new win.Event('mm-workspace-context'));assert.equal(win.document.querySelector('#mm-contract-workspace').hidden,true);assert.equal(win.document.querySelector('#spot-list').classList.contains('mm-contract-hidden'),false);win.dispatchEvent(new win.Event('pagehide'));dom.window.close();
});
test('research date jump restores the original workspace, URL and scroll without changing market',async()=>{
 const dom=new JSDOM('<main id="market-workspace-shell" data-market-scope="stocks" data-workspace="research-lab" data-instrument="stock:us:MU"><div id="center-workspace"></div></main>',{url:'https://test.invalid/?market=stocks&workspace=research-lab&instrument=stock:us:MU',runScripts:'outside-only',pretendToBeVisual:true}),win=dom.window,shell=win.document.querySelector('main');const calls=[];win.scrollTo=options=>calls.push(options.top);win.setMarketScope=market=>shell.dataset.marketScope=market;win.setWorkspaceInstrument=id=>shell.dataset.instrument=id;win.openWorkspace=id=>shell.dataset.workspace=id;win.MoneyMoneyChartBridge={locateDay:async(id,day)=>{calls.push([id,day]);return 1;}};
 win.eval(fs.readFileSync('src/web/public/workflow-polish.js','utf8'));await win.MoneyMoneyWorkflow.locate('2026-09-22T20:00:00Z','stock:us:MU');assert.equal(shell.dataset.workspace,'stock-quotes');assert.deepEqual(calls[0],['stock:us:MU','2026-09-22']);win.document.querySelector('#mm-return-to-research').click();await new Promise(r=>setTimeout(r,25));assert.equal(shell.dataset.workspace,'research-lab');assert.match(win.location.search,/research-lab/);assert.equal(calls.at(-1),0);dom.window.close();
});
test('contract subpanels request only selected datasets and preserve isolated instrument preferences',async()=>{
 const dom=new JSDOM('<main id="market-workspace-shell" data-market-scope="crypto" data-workspace="contracts" data-instrument="crypto:gateio:BTC_USDT"><div id="center-workspace"></div><aside data-market-library="crypto"></aside></main>',{url:'https://test.invalid',runScripts:'outside-only',pretendToBeVisual:true}),win=dom.window,calls=[];
 win.mm_isLoggedIn=true;win.mm_isGuest=false;win.MoneyTradingChart={render(){},clear(){},redraw(){}};
 win.fetch=async url=>{calls.push(url);const detail={success:true,instrument:'crypto:gateio:BTC_USDT',market:'crypto',dataStatus:'delayed',source:'Gate',updatedAt:'2026-10-08',kind:'perpetual',contract:'BTC_USDT',quote:{markPrice:100},sections:{funding:{dataStatus:'delayed',reason:null}},depth:{bids:[],asks:[],spreadPct:null},funding:[],series:{funding:{kind:'history',dataStatus:'delayed',reason:null,points:[],coverage:{records:0}}}};return{ok:true,json:async()=>url.includes('/catalog')?{success:true,items:[],dataStatus:'empty'}:url.includes('/kline')?{success:true,data:[],dataStatus:'empty'}:detail};};
 try {win.eval(fs.readFileSync('src/web/public/contracts-workspace.js','utf8'));win.document.dispatchEvent(new win.Event('DOMContentLoaded'));await new Promise(r=>setTimeout(r,20));
 assert.ok(calls.filter(url=>url.includes('/detail')).every(url=>new URL(url,'https://test.invalid').searchParams.get('panels')===''),'initial details must not request hidden data');
 const funding=win.document.querySelector('[data-contract-layer="funding"]');assert.ok(funding,'subpanel selector missing');funding.checked=true;funding.dispatchEvent(new win.Event('change'));await new Promise(r=>setTimeout(r,15));
 assert.equal(new URL(calls.filter(url=>url.includes('/detail')).at(-1),'https://test.invalid').searchParams.get('panels'),'funding');
 assert.doesNotMatch(win.document.querySelector('[data-contract-subpanels]').textContent,/来源没有此字段/,'successful source must not be labelled unavailable');
 assert.deepEqual(JSON.parse(win.localStorage.getItem('mm-contract-layers:crypto:gateio:BTC_USDT')),['volume','funding']);}finally{win.dispatchEvent(new win.Event('pagehide'));dom.window.close();}
});
