const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
process.env.MONEYMONEY_DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'mm-committee-test-'));
const file=path.resolve('dist/features/research-committee.js');
function setup(){assert.ok(fs.existsSync(file),'research committee service must exist');const {ResearchCommittee}=require(file),{SQLiteStateStore}=require('../dist/storage/sqlite-state'),{createEvidenceSnapshot}=require('../dist/features/decision-intelligence');const store=new SQLiteStateStore(path.join(fs.mkdtempSync(path.join(os.tmpdir(),'mm-committee-store-')),'state.sqlite'));const at=Date.now(),ev=createEvidenceSnapshot({market:'stocks',instrument:'stock:us:AAPL',workspace:'signals',dataStatus:'delayed',source:{id:'fixture',name:'Isolated fixture'},observedAt:new Date(at-60000).toISOString(),fetchedAt:new Date(at).toISOString(),fields:{price:100}});return {ResearchCommittee,store,ev};}
const input=(ev,key='committee-test-key-0001')=>({market:'stocks',instrument:'stock:us:AAPL',evidenceRefs:[ev.id],idempotencyKey:key});
const runtime={configured:true,apiKey:'test_key',apiUrl:'https://openrouter.ai/api/v1/chat/completions',model:'openrouter/free',chain:'openrouter'};
test('losing the lease during the last model call cannot publish a completed review',async()=>{const {ResearchCommittee,store,ev}=setup();const service=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>runtime,fetch:async(url,init)=>{const role=JSON.parse(JSON.parse(init.body).messages.at(-1).content).role;if(role==='risk'){const lease=store.getLease('research-committee:lease');store.releaseLease('research-committee:lease',lease.owner);store.acquireLease('research-committee:lease','new-owner',Date.now(),90000);}return response(ev,role);}});assert.equal((await service.run(input(ev))).status,'failed');store.close();});
test('legacy evidence aliases require the existing identity registry; unknown aliases are not guessed',async()=>{const {ResearchCommittee,store,ev}=setup();const {createEvidenceSnapshot}=require('../dist/features/decision-intelligence');const legacy=createEvidenceSnapshot({...ev,instrument:'AAPL'});const service=new ResearchCommittee({store,evidence:()=>legacy,resolve:(market,id)=>market==='stocks' && ['AAPL','usAAPL','stock:us:AAPL'].includes(id)?{id:'stock:us:AAPL'}:null,runtime:()=>({...runtime,configured:false})});assert.equal((await service.run({...input(legacy),instrument:'usAAPL'})).instrument,'stock:us:AAPL');await assert.rejects(service.run({...input(legacy,'unknown-identity-key'),instrument:'UNKNOWN'}),/身份/);store.close();});
test('model timeout is persisted without leaking an upstream error or continuing roles',async()=>{const {ResearchCommittee,store,ev}=setup();const service=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>runtime,timeoutMs:15,fetch:()=>new Promise(()=>{})});const result=await service.run(input(ev));assert.equal(result.status,'failed');assert.equal(result.calls,1);assert.ok(!store.getLease('research-committee:lease'));store.close();});
test('interrupted persisted review is closed as failed after its lease expires, not silently rerun',async()=>{const {ResearchCommittee,store,ev}=setup();const service=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>runtime,fetch:async()=>response(ev,'bull',{citations:['unknown']})});const result=await service.run(input(ev));const key='research-committee:request:'+require('node:crypto').createHash('sha256').update(JSON.stringify(input(ev).idempotencyKey)).digest('hex');store.set(key,{...result,status:'running'});assert.equal((await service.run(input(ev))).status,'failed');store.close();});
function response(ev,role,extra={}){return new Response(JSON.stringify({model:'fixture-model',choices:[{message:{content:JSON.stringify({role,stance:role==='bear'?'oppose':'uncertain',summary:'Fixture research summary',citations:[ev.id],risks:['Small sample'],...extra})}}]}));}
test('serial roles preserve citations and durable idempotency without any execution intent',async()=>{const {ResearchCommittee,store,ev}=setup();let calls=0;const deps={store,evidence:id=>id===ev.id?ev:null,runtime:()=>runtime,fetch:async(url,init)=>{const body=JSON.parse(init.body),role=JSON.parse(body.messages.at(-1).content).role;calls++;return response(ev,role);}};const service=new ResearchCommittee(deps);const result=await service.run(input(ev));assert.equal(result.status,'completed');assert.deepEqual(result.reviews.map(r=>r.role),['bull','bear','risk']);assert.equal(result.executionEnabled,false);assert.equal(result.calls,3);assert.equal((await new ResearchCommittee(deps).run(input(ev))).id,result.id);assert.equal(calls,3);assert.equal(service.list('crypto','crypto:binance:BTCUSDT').length,0);await assert.rejects(service.run({...input(ev),instrument:'stock:us:MU'}),/幂等|证据/);store.close();});
test('unknown citations and forbidden order fields fail closed without invoking the next role',async()=>{for(const extra of [{citations:['unknown']},{order:{action:'BUY'}}]){const {ResearchCommittee,store,ev}=setup();let n=0;const service=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>runtime,fetch:async()=>{n++;return response(ev,'bull',extra);}});const result=await service.run(input(ev));assert.equal(result.status,'failed');assert.equal(result.executionEnabled,false);assert.equal(n,1);store.close();}});
test('stale, future or cross-market evidence is rejected before consuming model budget',async()=>{for(const patch of [{market:'crypto'},{observedAt:'2020-01-01T00:00:00Z'},{observedAt:'2099-01-01T00:00:00Z'},{dataStatus:'unavailable'}]){const {ResearchCommittee,store,ev}=setup();let calls=0;const service=new ResearchCommittee({store,evidence:()=>({...ev,...patch}),runtime:()=>runtime,fetch:async()=>{calls++;throw Error('not called');}});await assert.rejects(service.run(input(ev)),/证据|时点|过期/);assert.equal(calls,0);store.close();}});
test('unconfigured and paid models never call upstream; reserved daily budget stops a ninth review',async()=>{const {ResearchCommittee,store,ev}=setup();const offline=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>({...runtime,configured:false}),fetch:async()=>{throw Error('not called');}});assert.equal((await offline.run(input(ev))).status,'unavailable');const paid=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>({...runtime,model:'paid-model'}),fetch:async()=>{throw Error('not called');}});assert.equal((await paid.run(input(ev,'committee-paid-0001'))).status,'unavailable');let n=0;const service=new ResearchCommittee({store,evidence:()=>ev,runtime:()=>runtime,fetch:async(url,init)=>{n++;return response(ev,JSON.parse(JSON.parse(init.body).messages.at(-1).content).role);}});for(let i=0;i<8;i++)assert.equal((await service.run(input(ev,'committee-budget-'+i))).status,'completed');const blocked=await service.run(input(ev,'committee-budget-9'));assert.equal(blocked.status,'unavailable');assert.match(blocked.reason,/额度/);assert.equal(n,24);store.close();});
test('concurrent workers share a lease, and risk opposition is recorded as veto, not an order',async()=>{const {ResearchCommittee,store,ev}=setup();let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r);const deps={store,evidence:()=>ev,runtime:()=>runtime,fetch:async(url,init)=>{const role=JSON.parse(JSON.parse(init.body).messages.at(-1).content).role;if(role==='bull'){started();await gate;}return response(ev,role,{stance:role==='risk'?'oppose':'support'});}};const a=new ResearchCommittee(deps),b=new ResearchCommittee(deps),work=a.run(input(ev));await ready;await assert.rejects(b.run(input(ev,'committee-parallel-2')),/运行/);release();const result=await work;assert.equal(result.veto,true);assert.equal(result.executionEnabled,false);store.close();});
